chore: test ls

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -103,7 +103,7 @@ jobs:
       - name: Debug coverage file
         run: |
           echo "Contents of coverage.json:"
-          ls -R ${{ github.workspace }}/reports || echo "Reports directory not found"
+          ls -R ${{ github.workspace }} || echo "Reports directory not found"
           ls -R ${{ github.workspace }}/reports/3.2-forest_admin_datasource_active_record || echo "Reports for active_record package not found"
           cat ${{ github.workspace }}/reports/3.2-forest_admin_datasource_active_record/coverage.json || echo "coverage.json not found"
 
