chore: update log

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -103,7 +103,8 @@ jobs:
       - name: Debug coverage file
         run: |
           echo "Contents of coverage.json:"
-          cat ${{ github.workspace }}/reports/3.2-forest_admin_datasource_active_record/coverage.json
+          ls -R ${{ github.workspace }}/reports || echo "Reports directory not found"
+          cat ${{ github.workspace }}/reports/3.2-forest_admin_datasource_active_record/coverage.json || echo "coverage.json not found"
 
       - name: Send coverage
         uses: paambaati/codeclimate-action@v5.0.0
